# Generated by Django 3.0.3 on 2020-05-18 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emallapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register',
            old_name='email',
            new_name='emails',
        ),
    ]
