# Generated by Django 3.0.3 on 2020-05-18 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emallapp', '0002_auto_20200518_2321'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register',
            old_name='emails',
            new_name='email',
        ),
    ]
