# Generated by Django 3.0.3 on 2020-05-21 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emallapp', '0004_nearestloc_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='nearestloc',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='emallapp.nearestloc'),
            preserve_default=False,
        ),
    ]
