# Generated by Django 3.0.3 on 2020-05-23 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emallapp', '0008_category_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description1',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
