# Generated by Django 3.0.3 on 2020-06-22 15:50

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('emallapp', '0010_auto_20200523_1418'),
    ]

    operations = [
        migrations.CreateModel(
            name='addproduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=255)),
                ('pimage', models.ImageField(null=True, upload_to='')),
                ('pdesc', models.CharField(max_length=2083)),
                ('price', models.IntegerField()),
                ('size', models.CharField(max_length=40, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')])),
                ('stock', models.IntegerField()),
            ],
        ),
    ]
