# Generated by Django 3.0.3 on 2020-06-22 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emallapp', '0012_auto_20200622_2123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addproduct',
            name='pimage',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
