# Generated by Django 3.0.3 on 2020-06-22 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emallapp', '0013_auto_20200622_2155'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='c_name',
        ),
        migrations.AddField(
            model_name='addproduct',
            name='c_name',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='emallapp.Category'),
            preserve_default=False,
        ),
    ]
