# Generated by Django 3.0.3 on 2020-06-22 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emallapp', '0014_auto_20200622_2240'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addproduct',
            old_name='c_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='c_name',
            new_name='name',
        ),
    ]
