# Generated by Django 3.0.3 on 2020-06-22 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emallapp', '0015_auto_20200622_2249'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addproduct',
            old_name='name',
            new_name='c_name',
        ),
    ]
