# Generated by Django 3.0.3 on 2020-08-10 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emallapp', '0017_auto_20200622_2328'),
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=15, unique=True)),
                ('password', models.CharField(max_length=8)),
            ],
        ),
    ]
