# Generated by Django 3.0.3 on 2020-08-10 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emallapp', '0018_login'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Login',
        ),
    ]
